// Generated by CoffeeScript 1.6.3
(function() {
  var ModelIndex, mongoose;

  mongoose = require('mongoose');

  module.exports = ModelIndex = (function() {
    function ModelIndex() {}

    ModelIndex.cache = {};

    ModelIndex.fetch = function(name, schema) {
      if (!this.cache[name]) {
        this.cache[name] = mongoose.model(name, schema);
      }
      return this.cache[name];
    };

    return ModelIndex;

  })();

}).call(this);
